services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image: zananpech/obesity-classifier-group17:54957a8 
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
