# File below is adapted from work by Tiffany A. Timbers in breast-cancer-predictor repository
# https://github.com/ttimbers/breast-cancer-predictor/blob/main/docker-compose.yml

services:
  # run jupyter notebook inside jupyter
  jupyter-notebook:
    image: zananpech/obesity-classifier-group17:f8cb4db
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
