name: obesity_classifier_group17
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.5
  - matplotlib=3.9.2
  - pandas=2.1.2
  - altair=5.1.2
  - ipykernel=6.26.0
  - notebook=6.5.4
  - python=3.11
  - requests=2.31.0
  - scikit-learn=1.5.1
  - conda-lock=2.5.7
  - numpy=1.26.0
  - vegafusion-python-embed=1.4.3
  - vegafusion=1.4.3
  - vl-convert-python=1.0.1
  - ucimlrepo==0.0.7
  - pandera=0.21.0
  - pip=24.3.1
  - click=8.1.7
  - quarto=1.5.57
  - tabulate=0.9.0
  - pip:
      - deepchecks==0.18.1
