name: obesity_classifier_group17
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab>=3.5
  - matplotlib=3.9.2
  - pandas=2.1.2
  - altair=5.1.2
  - ipykernel=6.26.0
  - notebook=6.5.4
  - python=3.11
  - requests=2.31.0
  - scikit-learn=1.5.1
  - conda-lock=2.5.7
  - numpy=1.26.0
  - pip>=24.2
  - vegafusion-python-embed=1.4.3
  - vegafusion=1.4.3
  - vl-convert-python=1.0.1
  - pip:
      - transformers
      - ucimlrepo
